#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu Oct 08 09:55:23 GMT-03:00 2026
prefixes-apache.snapshots.txt.lastUpdated=1791461936135
prefixes-central-snapshots.txt.error=
prefixes-central-snapshots.txt.lastUpdated=1791461934513
prefixes-central.txt.error=Could not transfer metadata /.meta/prefixes.txt from/to central (https\://repo.maven.apache.org/maven2)\: Permission denied
prefixes-central.txt/@default-central-https\://repo.maven.apache.org/maven2/.lastUpdated=1791461900598
prefixes-flyway-community-db-support.txt.error=Could not transfer metadata /.meta/prefixes.txt from/to flyway-community-db-support (https\://maven.pkg.github.com/flyway/flyway-community-db-support)\: HTTP Status\: 401
prefixes-flyway-community-db-support.txt/@default-flyway-community-db-support-https\://maven.pkg.github.com/flyway/flyway-community-db-support/.lastUpdated=1791464123271
prefixes-jboss-public-repository-group.txt.error=
prefixes-jboss-public-repository-group.txt.lastUpdated=1791419199201
prefixes-maven-central.txt.lastUpdated=1791461937657
prefixes-ow2-snapshot.txt.lastUpdated=1791461959164
prefixes-plexus.snapshots.txt.error=
prefixes-plexus.snapshots.txt.lastUpdated=1791461936617
prefixes-redshift.txt.error=
prefixes-redshift.txt.lastUpdated=1791461938756
prefixes-repo.gradle.org.txt.error=
prefixes-repo.gradle.org.txt.lastUpdated=1791461938291
