#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Wed Oct 07 21:38:02 GMT-03:00 2026
prefixes-central.txt.error=Could not transfer metadata /.meta/prefixes.txt from/to central (https\://repo.maven.apache.org/maven2)\: Permission denied
prefixes-central.txt/@default-central-https\://repo.maven.apache.org/maven2/.lastUpdated=1791419882226
